# use Ganache's forked mainnet mode as the default network
dotenv: .env

project_structure:
  contracts: lib/core/contracts

# NOTE: You don't *have* to do this, but it is often helpful for testing
networks:
  default: mainnet-fork

# automatically fetch contract sources from Etherscan
autofetch_sources: True

# path remapping to support imports from GitHub/NPM
compiler:
  solc:
    version: 0.8.17
    remappings:
      - "solmate=transmissions11/v6/src/"
reports:
  exclude_contracts:
